### ISSUE TITLE
release 0.1.0

### ISSUE THREAD

**Issue by keewis** [xarray-contrib/xdggs#75]
Since the last dev release almost a year ago, a lot has changed in the library:
- grid info objects to allow non-conforming metadata, and as a layer to contain all the API weirdness of the implementing libraries
- replace the `assign_*` methods with property methods (inspired by `xarray`'s `.dt` and `.str` accessors)
- lots of tests!
- the computation of cell boundaries
- most recently, the visualization using `lonboard`

This is definitely enough for a release! However, to be useful we really need some documentation, which I think has to be done before the release (API documentation plus one tutorial for each DGGS should be sufficient for now). For the tutorials, I think we want to resolve #71 first.

I think this is the items needed :
- [x] #64 (breaking change, should be done now where there's not as many users affected)
- [x] #71: #84 and [xdggs-data](https://github.com/xdggs/xdggs-data)
- [x] #76
- [x] ~#56~ (punted to a later release)
